// Generated by Selenium IDE
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;
public class FlightBookingTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void flightBooking() {
    driver.get("https://phptravels.com/");
    driver.manage().window().setSize(new Dimension(1440, 819));
    driver.findElement(By.linkText("Demo")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".wow:nth-child(2) small:nth-child(1)")).click();
    vars.put("win8677", waitForWindow(2000));
    driver.switchTo().window(vars.get("win8677").toString());
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("admin@phptravels.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("demoadmin");
    driver.findElement(By.cssSelector(".btn-lg")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("nav > ul > li:nth-child(3) > .waves-effect"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("nav > ul > li:nth-child(3) > .waves-effect")).click();
    driver.findElement(By.cssSelector(".col-lg-4:nth-child(1) h6")).click();
    driver.findElement(By.id("autocomplete")).click();
    driver.findElement(By.cssSelector(".autocomplete-result:nth-child(1) > .autocomplete-location")).click();
    driver.findElement(By.id("autocomplete2")).click();
    driver.findElement(By.cssSelector(".autocomplete-result:nth-child(1) strong")).click();
    driver.findElement(By.id("departure")).click();
    driver.findElement(By.cssSelector(".datepicker:nth-child(28) tr:nth-child(3) > .day:nth-child(7)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".guest_flights"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".guest_flights")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".dropdown-item:nth-child(1) .qtyInc > .la")).click();
    driver.findElement(By.cssSelector(".mdi-search")).click();
    driver.findElement(By.cssSelector(".header-right-action:nth-child(3) #currency")).click();
    {
      WebElement element = driver.findElement(By.linkText("Logout"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Logout")).click();
  }
}
