// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.chrome.
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class LoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void login() {
    driver.get("https://phptravels.com/demo");
    driver.manage().window().setSize(new Dimension(1440, 819));
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".wow:nth-child(2) small:nth-child(1)")).click();
    vars.put("win5355", waitForWindow(2000));
    vars.put("root", driver.getWindowHandle());
    driver.switchTo().window(vars.get("win5355").toString());
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.cssSelector(".wow:nth-child(2) .col-md-10")).click();
    driver.switchTo().window(vars.get("win5355").toString());
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("admin@phptravels.com");
    driver.switchTo().window(vars.get("root").toString());
    driver.findElement(By.cssSelector(".wow:nth-child(2) .col-md-10")).click();
    driver.switchTo().window(vars.get("win5355").toString());
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("demoadmin");
    driver.findElement(By.cssSelector(".btn-default > .ladda-label")).click();
    {
      WebElement element = driver.findElement(By.linkText("Logout"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Logout")).click();
  }
}
