# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUpdateprofile():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_updateprofile(self):
    self.driver.get("https://phptravels.com/demo")
    self.driver.set_window_size(1440, 819)
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".wow:nth-child(2) small:nth-child(1)").click()
    self.vars["win4832"] = self.wait_for_window(2000)
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.switch_to.window(self.vars["win4832"])
    self.vars["win9667"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win9667"])
    self.driver.switch_to.window(self.vars["win4832"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["win9667"])
    self.driver.find_element(By.LINK_TEXT, "My Profile").click()
    self.driver.find_element(By.NAME, "phone").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".theme-btn:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.NAME, "phone").send_keys("98765")
    self.driver.find_element(By.CSS_SELECTOR, ".theme-btn:nth-child(1)").click()
  
